import "@/style/main.scss";

import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/Footer'
import Notification from '@/components/Notification'

import { NotificationProvider } from '@/contexts/NotificationContext'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NotificationProvider>
          <Notification />
          <Navbar />
          {children}
          <Footer />
        </NotificationProvider>
      </body>
    </html>
  );
}
